name: Type Check

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.3.0' 

      - name: Install dependencies
        run: npm install

      - name: Run type checks
        run: npm run type-check

      - name: Run build
        run: npm run build
